---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kastellan.useurmind.de
  resources:
  - dockerstacks
  - externalhostgroups
  - externalhosts
  - podmanplays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kastellan.useurmind.de
  resources:
  - dockerstacks/finalizers
  - externalhostgroups/finalizers
  - externalhosts/finalizers
  - podmanplays/finalizers
  verbs:
  - update
- apiGroups:
  - kastellan.useurmind.de
  resources:
  - dockerstacks/status
  - externalhostgroups/status
  - externalhosts/status
  - podmanplays/status
  verbs:
  - get
  - patch
  - update
