// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: kastellan/agent/v1alpha1/agent.proto

package agentv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentProtocol_Connect_FullMethodName = "/kastellan.agent.v1alpha1.AgentProtocol/Connect"
)

// AgentProtocolClient is the client API for AgentProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Protocol service definition for bidirectional streaming.
type AgentProtocolClient interface {
	// Connect establishes a bidirectional stream for protocol messages.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProtocolMessage, ProtocolMessage], error)
}

type agentProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentProtocolClient(cc grpc.ClientConnInterface) AgentProtocolClient {
	return &agentProtocolClient{cc}
}

func (c *agentProtocolClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProtocolMessage, ProtocolMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentProtocol_ServiceDesc.Streams[0], AgentProtocol_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProtocolMessage, ProtocolMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentProtocol_ConnectClient = grpc.BidiStreamingClient[ProtocolMessage, ProtocolMessage]

// AgentProtocolServer is the server API for AgentProtocol service.
// All implementations must embed UnimplementedAgentProtocolServer
// for forward compatibility.
//
// Protocol service definition for bidirectional streaming.
type AgentProtocolServer interface {
	// Connect establishes a bidirectional stream for protocol messages.
	Connect(grpc.BidiStreamingServer[ProtocolMessage, ProtocolMessage]) error
	mustEmbedUnimplementedAgentProtocolServer()
}

// UnimplementedAgentProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentProtocolServer struct{}

func (UnimplementedAgentProtocolServer) Connect(grpc.BidiStreamingServer[ProtocolMessage, ProtocolMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentProtocolServer) mustEmbedUnimplementedAgentProtocolServer() {}
func (UnimplementedAgentProtocolServer) testEmbeddedByValue()                       {}

// UnsafeAgentProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentProtocolServer will
// result in compilation errors.
type UnsafeAgentProtocolServer interface {
	mustEmbedUnimplementedAgentProtocolServer()
}

func RegisterAgentProtocolServer(s grpc.ServiceRegistrar, srv AgentProtocolServer) {
	// If the following call panics, it indicates UnimplementedAgentProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentProtocol_ServiceDesc, srv)
}

func _AgentProtocol_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentProtocolServer).Connect(&grpc.GenericServerStream[ProtocolMessage, ProtocolMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentProtocol_ConnectServer = grpc.BidiStreamingServer[ProtocolMessage, ProtocolMessage]

// AgentProtocol_ServiceDesc is the grpc.ServiceDesc for AgentProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kastellan.agent.v1alpha1.AgentProtocol",
	HandlerType: (*AgentProtocolServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentProtocol_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kastellan/agent/v1alpha1/agent.proto",
}
