// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/kastellan/agent/v1alpha1/agent.proto

package agentv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtocolVersion represents a version number.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// ResourceIdentity uniquely identifies a Kubernetes resource.
type ResourceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Generation    int64                  `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceIdentity) Reset() {
	*x = ResourceIdentity{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIdentity) ProtoMessage() {}

func (x *ResourceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIdentity.ProtoReflect.Descriptor instead.
func (*ResourceIdentity) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceIdentity) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ResourceIdentity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceIdentity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceIdentity) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// ErrorDetail provides detailed error information.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// RuntimeInformation provides information about the runtime environment.
type RuntimeInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInformation) Reset() {
	*x = RuntimeInformation{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInformation) ProtoMessage() {}

func (x *RuntimeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInformation.ProtoReflect.Descriptor instead.
func (*RuntimeInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeInformation) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RuntimeHealth provides runtime health status.
type RuntimeHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeHealth) Reset() {
	*x = RuntimeHealth{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeHealth) ProtoMessage() {}

func (x *RuntimeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeHealth.ProtoReflect.Descriptor instead.
func (*RuntimeHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeHealth) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *RuntimeHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ContainerInfo represents information about a container.
type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// WorkloadResult represents the result for a single workload.
type WorkloadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workload identification
	Identity *ResourceIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Current phase
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// Error details if phase is Failed
	Error *ErrorDetail `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Manifest digest
	ManifestDigest string `protobuf:"bytes,4,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	// Runtime information
	Runtime       *RuntimeInformation `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Containers    []*ContainerInfo    `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadResult) Reset() {
	*x = WorkloadResult{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadResult) ProtoMessage() {}

func (x *WorkloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadResult.ProtoReflect.Descriptor instead.
func (*WorkloadResult) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *WorkloadResult) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *WorkloadResult) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WorkloadResult) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *WorkloadResult) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *WorkloadResult) GetRuntime() *RuntimeInformation {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *WorkloadResult) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

// LocalWorkload represents a workload assigned to the agent.
type LocalWorkload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identity       *ResourceIdentity      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Manifest       string                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalWorkload) Reset() {
	*x = LocalWorkload{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalWorkload) ProtoMessage() {}

func (x *LocalWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalWorkload.ProtoReflect.Descriptor instead.
func (*LocalWorkload) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *LocalWorkload) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *LocalWorkload) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *LocalWorkload) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

// PodmanPlayAssignment represents a Podman play workload assignment.
type PodmanPlayAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identity       *ResourceIdentity      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Manifest       string                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	UpdateStrategy string                 `protobuf:"bytes,4,opt,name=update_strategy,json=updateStrategy,proto3" json:"update_strategy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PodmanPlayAssignment) Reset() {
	*x = PodmanPlayAssignment{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodmanPlayAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodmanPlayAssignment) ProtoMessage() {}

func (x *PodmanPlayAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodmanPlayAssignment.ProtoReflect.Descriptor instead.
func (*PodmanPlayAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PodmanPlayAssignment) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PodmanPlayAssignment) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *PodmanPlayAssignment) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *PodmanPlayAssignment) GetUpdateStrategy() string {
	if x != nil {
		return x.UpdateStrategy
	}
	return ""
}

// AgentHello is the initial connection message sent by the agent.
type AgentHello struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostName             string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	AgentVersion         string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SupportedProtocols   []*ProtocolVersion     `protobuf:"bytes,4,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	Runtime              *RuntimeInformation    `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	LastSessionId        string                 `protobuf:"bytes,6,opt,name=last_session_id,json=lastSessionId,proto3" json:"last_session_id,omitempty"`
	LastReceivedRevision uint64                 `protobuf:"varint,7,opt,name=last_received_revision,json=lastReceivedRevision,proto3" json:"last_received_revision,omitempty"`
	LastAppliedRevision  uint64                 `protobuf:"varint,8,opt,name=last_applied_revision,json=lastAppliedRevision,proto3" json:"last_applied_revision,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetSupportedProtocols() []*ProtocolVersion {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *AgentHello) GetRuntime() *RuntimeInformation {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *AgentHello) GetLastSessionId() string {
	if x != nil {
		return x.LastSessionId
	}
	return ""
}

func (x *AgentHello) GetLastReceivedRevision() uint64 {
	if x != nil {
		return x.LastReceivedRevision
	}
	return 0
}

func (x *AgentHello) GetLastAppliedRevision() uint64 {
	if x != nil {
		return x.LastAppliedRevision
	}
	return 0
}

// OperatorHello is the server's response to AgentHello.
type OperatorHello struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SessionId                  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SelectedProtocol           *ProtocolVersion       `protobuf:"bytes,2,opt,name=selected_protocol,json=selectedProtocol,proto3" json:"selected_protocol,omitempty"`
	HeartbeatIntervalSeconds   uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	StateReportIntervalSeconds uint32                 `protobuf:"varint,4,opt,name=state_report_interval_seconds,json=stateReportIntervalSeconds,proto3" json:"state_report_interval_seconds,omitempty"`
	ServerTimeUnix             int64                  `protobuf:"varint,5,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *OperatorHello) Reset() {
	*x = OperatorHello{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorHello) ProtoMessage() {}

func (x *OperatorHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorHello.ProtoReflect.Descriptor instead.
func (*OperatorHello) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *OperatorHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OperatorHello) GetSelectedProtocol() *ProtocolVersion {
	if x != nil {
		return x.SelectedProtocol
	}
	return nil
}

func (x *OperatorHello) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *OperatorHello) GetStateReportIntervalSeconds() uint32 {
	if x != nil {
		return x.StateReportIntervalSeconds
	}
	return 0
}

func (x *OperatorHello) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

// DesiredState is sent by the operator to deliver workload assignments.
type DesiredState struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Host          string                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Revision      uint64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	PodmanPlays   []*PodmanPlayAssignment `protobuf:"bytes,3,rep,name=podman_plays,json=podmanPlays,proto3" json:"podman_plays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DesiredState) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DesiredState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredState) GetPodmanPlays() []*PodmanPlayAssignment {
	if x != nil {
		return x.PodmanPlays
	}
	return nil
}

// DesiredStateUpdate is sent by the operator for incremental updates.
type DesiredStateUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionId     string                  `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Host          string                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Revision      uint64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Additions     []*PodmanPlayAssignment `protobuf:"bytes,4,rep,name=additions,proto3" json:"additions,omitempty"`
	Deletions     []string                `protobuf:"bytes,5,rep,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredStateUpdate) Reset() {
	*x = DesiredStateUpdate{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredStateUpdate) ProtoMessage() {}

func (x *DesiredStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredStateUpdate.ProtoReflect.Descriptor instead.
func (*DesiredStateUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DesiredStateUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DesiredStateUpdate) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DesiredStateUpdate) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredStateUpdate) GetAdditions() []*PodmanPlayAssignment {
	if x != nil {
		return x.Additions
	}
	return nil
}

func (x *DesiredStateUpdate) GetDeletions() []string {
	if x != nil {
		return x.Deletions
	}
	return nil
}

// Heartbeat is a periodic status update from the agent.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Runtime       *RuntimeHealth         `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Workloads     *WorkloadStatus        `protobuf:"bytes,3,opt,name=workloads,proto3" json:"workloads,omitempty"`
	HostName      string                 `protobuf:"bytes,4,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *Heartbeat) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Heartbeat) GetRuntime() *RuntimeHealth {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *Heartbeat) GetWorkloads() *WorkloadStatus {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *Heartbeat) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

// HostInventory is sent by the agent to report host capabilities.
type HostInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Host          *HostInfo              `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Podman        *PodmanInfo            `protobuf:"bytes,3,opt,name=podman,proto3" json:"podman,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInventory) Reset() {
	*x = HostInventory{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInventory) ProtoMessage() {}

func (x *HostInventory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInventory.ProtoReflect.Descriptor instead.
func (*HostInventory) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *HostInventory) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HostInventory) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *HostInventory) GetPodman() *PodmanInfo {
	if x != nil {
		return x.Podman
	}
	return nil
}

func (x *HostInventory) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ReconcileResult reports the result of workload reconciliation.
type ReconcileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Workloads     []*WorkloadResult      `protobuf:"bytes,4,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResult) Reset() {
	*x = ReconcileResult{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResult) ProtoMessage() {}

func (x *ReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResult.ProtoReflect.Descriptor instead.
func (*ReconcileResult) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReconcileResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReconcileResult) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReconcileResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ReconcileResult) GetWorkloads() []*WorkloadResult {
	if x != nil {
		return x.Workloads
	}
	return nil
}

// ReconcileRequest is sent by the operator to request reconciliation.
type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ReconcileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReconcileRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReconcileRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// WorkloadStatus reports the status of a single workload.
type WorkloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Identity      *ResourceIdentity      `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Runtime       *RuntimeInformation    `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *WorkloadStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkloadStatus) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *WorkloadStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WorkloadStatus) GetRuntime() *RuntimeInformation {
	if x != nil {
		return x.Runtime
	}
	return nil
}

// ProtocolMessage is a wrapper for all protocol messages using oneof.
type ProtocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProtocolMessage_AgentHello
	//	*ProtocolMessage_EnrollmentRequest
	//	*ProtocolMessage_Heartbeat
	//	*ProtocolMessage_HostInventory
	//	*ProtocolMessage_ReconcileResult
	//	*ProtocolMessage_WorkloadStatus
	//	*ProtocolMessage_CertificateRotationRequest
	//	*ProtocolMessage_OperatorHello
	//	*ProtocolMessage_EnrollmentResponse
	//	*ProtocolMessage_DesiredState
	//	*ProtocolMessage_DesiredStateUpdate
	//	*ProtocolMessage_ReconcileRequest
	//	*ProtocolMessage_CertificateRotationResponse
	//	*ProtocolMessage_ConnectionClose
	//	*ProtocolMessage_ProtocolVersion
	//	*ProtocolMessage_ResourceIdentity
	//	*ProtocolMessage_ErrorDetail
	//	*ProtocolMessage_RuntimeInformation
	//	*ProtocolMessage_ContainerInfo
	//	*ProtocolMessage_WorkloadResult
	//	*ProtocolMessage_LocalWorkload
	//	*ProtocolMessage_PodmanPlayAssignment
	//	*ProtocolMessage_RuntimeHealth
	//	*ProtocolMessage_HostInfo
	//	*ProtocolMessage_PodmanInfo
	Payload       isProtocolMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ProtocolMessage) GetPayload() isProtocolMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtocolMessage) GetAgentHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_AgentHello); ok {
			return x.AgentHello
		}
	}
	return nil
}

func (x *ProtocolMessage) GetEnrollmentRequest() string {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_EnrollmentRequest); ok {
			return x.EnrollmentRequest
		}
	}
	return ""
}

func (x *ProtocolMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProtocolMessage) GetHostInventory() *HostInventory {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_HostInventory); ok {
			return x.HostInventory
		}
	}
	return nil
}

func (x *ProtocolMessage) GetReconcileResult() *ReconcileResult {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ReconcileResult); ok {
			return x.ReconcileResult
		}
	}
	return nil
}

func (x *ProtocolMessage) GetWorkloadStatus() *WorkloadStatus {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_WorkloadStatus); ok {
			return x.WorkloadStatus
		}
	}
	return nil
}

func (x *ProtocolMessage) GetCertificateRotationRequest() string {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_CertificateRotationRequest); ok {
			return x.CertificateRotationRequest
		}
	}
	return ""
}

func (x *ProtocolMessage) GetOperatorHello() *OperatorHello {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_OperatorHello); ok {
			return x.OperatorHello
		}
	}
	return nil
}

func (x *ProtocolMessage) GetEnrollmentResponse() string {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_EnrollmentResponse); ok {
			return x.EnrollmentResponse
		}
	}
	return ""
}

func (x *ProtocolMessage) GetDesiredState() *DesiredState {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_DesiredState); ok {
			return x.DesiredState
		}
	}
	return nil
}

func (x *ProtocolMessage) GetDesiredStateUpdate() *DesiredStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_DesiredStateUpdate); ok {
			return x.DesiredStateUpdate
		}
	}
	return nil
}

func (x *ProtocolMessage) GetReconcileRequest() *ReconcileRequest {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ReconcileRequest); ok {
			return x.ReconcileRequest
		}
	}
	return nil
}

func (x *ProtocolMessage) GetCertificateRotationResponse() string {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_CertificateRotationResponse); ok {
			return x.CertificateRotationResponse
		}
	}
	return ""
}

func (x *ProtocolMessage) GetConnectionClose() string {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ConnectionClose); ok {
			return x.ConnectionClose
		}
	}
	return ""
}

func (x *ProtocolMessage) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ProtocolVersion); ok {
			return x.ProtocolVersion
		}
	}
	return nil
}

func (x *ProtocolMessage) GetResourceIdentity() *ResourceIdentity {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ResourceIdentity); ok {
			return x.ResourceIdentity
		}
	}
	return nil
}

func (x *ProtocolMessage) GetErrorDetail() *ErrorDetail {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ErrorDetail); ok {
			return x.ErrorDetail
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRuntimeInformation() *RuntimeInformation {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_RuntimeInformation); ok {
			return x.RuntimeInformation
		}
	}
	return nil
}

func (x *ProtocolMessage) GetContainerInfo() *ContainerInfo {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_ContainerInfo); ok {
			return x.ContainerInfo
		}
	}
	return nil
}

func (x *ProtocolMessage) GetWorkloadResult() *WorkloadResult {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_WorkloadResult); ok {
			return x.WorkloadResult
		}
	}
	return nil
}

func (x *ProtocolMessage) GetLocalWorkload() *LocalWorkload {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_LocalWorkload); ok {
			return x.LocalWorkload
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPodmanPlayAssignment() *PodmanPlayAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_PodmanPlayAssignment); ok {
			return x.PodmanPlayAssignment
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRuntimeHealth() *RuntimeHealth {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_RuntimeHealth); ok {
			return x.RuntimeHealth
		}
	}
	return nil
}

func (x *ProtocolMessage) GetHostInfo() *HostInfo {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_HostInfo); ok {
			return x.HostInfo
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPodmanInfo() *PodmanInfo {
	if x != nil {
		if x, ok := x.Payload.(*ProtocolMessage_PodmanInfo); ok {
			return x.PodmanInfo
		}
	}
	return nil
}

type isProtocolMessage_Payload interface {
	isProtocolMessage_Payload()
}

type ProtocolMessage_AgentHello struct {
	// Agent messages
	AgentHello *AgentHello `protobuf:"bytes,1,opt,name=agent_hello,json=agentHello,proto3,oneof"`
}

type ProtocolMessage_EnrollmentRequest struct {
	EnrollmentRequest string `protobuf:"bytes,2,opt,name=enrollment_request,json=enrollmentRequest,proto3,oneof"`
}

type ProtocolMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type ProtocolMessage_HostInventory struct {
	HostInventory *HostInventory `protobuf:"bytes,4,opt,name=host_inventory,json=hostInventory,proto3,oneof"`
}

type ProtocolMessage_ReconcileResult struct {
	ReconcileResult *ReconcileResult `protobuf:"bytes,5,opt,name=reconcile_result,json=reconcileResult,proto3,oneof"`
}

type ProtocolMessage_WorkloadStatus struct {
	WorkloadStatus *WorkloadStatus `protobuf:"bytes,6,opt,name=workload_status,json=workloadStatus,proto3,oneof"`
}

type ProtocolMessage_CertificateRotationRequest struct {
	CertificateRotationRequest string `protobuf:"bytes,7,opt,name=certificate_rotation_request,json=certificateRotationRequest,proto3,oneof"`
}

type ProtocolMessage_OperatorHello struct {
	// Operator messages
	OperatorHello *OperatorHello `protobuf:"bytes,8,opt,name=operator_hello,json=operatorHello,proto3,oneof"`
}

type ProtocolMessage_EnrollmentResponse struct {
	EnrollmentResponse string `protobuf:"bytes,9,opt,name=enrollment_response,json=enrollmentResponse,proto3,oneof"`
}

type ProtocolMessage_DesiredState struct {
	DesiredState *DesiredState `protobuf:"bytes,10,opt,name=desired_state,json=desiredState,proto3,oneof"`
}

type ProtocolMessage_DesiredStateUpdate struct {
	DesiredStateUpdate *DesiredStateUpdate `protobuf:"bytes,11,opt,name=desired_state_update,json=desiredStateUpdate,proto3,oneof"`
}

type ProtocolMessage_ReconcileRequest struct {
	ReconcileRequest *ReconcileRequest `protobuf:"bytes,12,opt,name=reconcile_request,json=reconcileRequest,proto3,oneof"`
}

type ProtocolMessage_CertificateRotationResponse struct {
	CertificateRotationResponse string `protobuf:"bytes,13,opt,name=certificate_rotation_response,json=certificateRotationResponse,proto3,oneof"`
}

type ProtocolMessage_ConnectionClose struct {
	ConnectionClose string `protobuf:"bytes,14,opt,name=connection_close,json=connectionClose,proto3,oneof"`
}

type ProtocolMessage_ProtocolVersion struct {
	// Common types
	ProtocolVersion *ProtocolVersion `protobuf:"bytes,15,opt,name=protocol_version,json=protocolVersion,proto3,oneof"`
}

type ProtocolMessage_ResourceIdentity struct {
	ResourceIdentity *ResourceIdentity `protobuf:"bytes,16,opt,name=resource_identity,json=resourceIdentity,proto3,oneof"`
}

type ProtocolMessage_ErrorDetail struct {
	ErrorDetail *ErrorDetail `protobuf:"bytes,17,opt,name=error_detail,json=errorDetail,proto3,oneof"`
}

type ProtocolMessage_RuntimeInformation struct {
	RuntimeInformation *RuntimeInformation `protobuf:"bytes,18,opt,name=runtime_information,json=runtimeInformation,proto3,oneof"`
}

type ProtocolMessage_ContainerInfo struct {
	ContainerInfo *ContainerInfo `protobuf:"bytes,19,opt,name=container_info,json=containerInfo,proto3,oneof"`
}

type ProtocolMessage_WorkloadResult struct {
	WorkloadResult *WorkloadResult `protobuf:"bytes,20,opt,name=workload_result,json=workloadResult,proto3,oneof"`
}

type ProtocolMessage_LocalWorkload struct {
	LocalWorkload *LocalWorkload `protobuf:"bytes,21,opt,name=local_workload,json=localWorkload,proto3,oneof"`
}

type ProtocolMessage_PodmanPlayAssignment struct {
	PodmanPlayAssignment *PodmanPlayAssignment `protobuf:"bytes,22,opt,name=podman_play_assignment,json=podmanPlayAssignment,proto3,oneof"`
}

type ProtocolMessage_RuntimeHealth struct {
	RuntimeHealth *RuntimeHealth `protobuf:"bytes,23,opt,name=runtime_health,json=runtimeHealth,proto3,oneof"`
}

type ProtocolMessage_HostInfo struct {
	HostInfo *HostInfo `protobuf:"bytes,24,opt,name=host_info,json=hostInfo,proto3,oneof"`
}

type ProtocolMessage_PodmanInfo struct {
	PodmanInfo *PodmanInfo `protobuf:"bytes,25,opt,name=podman_info,json=podmanInfo,proto3,oneof"`
}

func (*ProtocolMessage_AgentHello) isProtocolMessage_Payload() {}

func (*ProtocolMessage_EnrollmentRequest) isProtocolMessage_Payload() {}

func (*ProtocolMessage_Heartbeat) isProtocolMessage_Payload() {}

func (*ProtocolMessage_HostInventory) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ReconcileResult) isProtocolMessage_Payload() {}

func (*ProtocolMessage_WorkloadStatus) isProtocolMessage_Payload() {}

func (*ProtocolMessage_CertificateRotationRequest) isProtocolMessage_Payload() {}

func (*ProtocolMessage_OperatorHello) isProtocolMessage_Payload() {}

func (*ProtocolMessage_EnrollmentResponse) isProtocolMessage_Payload() {}

func (*ProtocolMessage_DesiredState) isProtocolMessage_Payload() {}

func (*ProtocolMessage_DesiredStateUpdate) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ReconcileRequest) isProtocolMessage_Payload() {}

func (*ProtocolMessage_CertificateRotationResponse) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ConnectionClose) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ProtocolVersion) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ResourceIdentity) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ErrorDetail) isProtocolMessage_Payload() {}

func (*ProtocolMessage_RuntimeInformation) isProtocolMessage_Payload() {}

func (*ProtocolMessage_ContainerInfo) isProtocolMessage_Payload() {}

func (*ProtocolMessage_WorkloadResult) isProtocolMessage_Payload() {}

func (*ProtocolMessage_LocalWorkload) isProtocolMessage_Payload() {}

func (*ProtocolMessage_PodmanPlayAssignment) isProtocolMessage_Payload() {}

func (*ProtocolMessage_RuntimeHealth) isProtocolMessage_Payload() {}

func (*ProtocolMessage_HostInfo) isProtocolMessage_Payload() {}

func (*ProtocolMessage_PodmanInfo) isProtocolMessage_Payload() {}

// HostInfo provides host system information.
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Cpu           string                 `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       string                 `protobuf:"bytes,7,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *HostInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HostInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *HostInfo) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *HostInfo) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

// PodmanInfo provides Podman runtime information.
type PodmanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Rootful       bool                   `protobuf:"varint,2,opt,name=rootful,proto3" json:"rootful,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodmanInfo) Reset() {
	*x = PodmanInfo{}
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodmanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodmanInfo) ProtoMessage() {}

func (x *PodmanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodmanInfo.ProtoReflect.Descriptor instead.
func (*PodmanInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *PodmanInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PodmanInfo) GetRootful() bool {
	if x != nil {
		return x.Rootful
	}
	return false
}

func (x *PodmanInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

var File_api_proto_kastellan_agent_v1alpha1_agent_proto protoreflect.FileDescriptor

const file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDesc = "" +
	"\n" +
	".api/proto/kastellan/agent/v1alpha1/agent.proto\x12\x18kastellan.agent.v1alpha1\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\xab\x01\n" +
	"\x10ResourceIdentity\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x03R\n" +
	"generation\"Y\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"f\n" +
	"\x12RuntimeInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"G\n" +
	"\rRuntimeHealth\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\rContainerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\xe5\x02\n" +
	"\x0eWorkloadResult\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.kastellan.agent.v1alpha1.ResourceIdentityR\bidentity\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12;\n" +
	"\x05error\x18\x03 \x01(\v2%.kastellan.agent.v1alpha1.ErrorDetailR\x05error\x12'\n" +
	"\x0fmanifest_digest\x18\x04 \x01(\tR\x0emanifestDigest\x12F\n" +
	"\aruntime\x18\x05 \x01(\v2,.kastellan.agent.v1alpha1.RuntimeInformationR\aruntime\x12G\n" +
	"\n" +
	"containers\x18\x06 \x03(\v2'.kastellan.agent.v1alpha1.ContainerInfoR\n" +
	"containers\"\x9c\x01\n" +
	"\rLocalWorkload\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.kastellan.agent.v1alpha1.ResourceIdentityR\bidentity\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\tR\bmanifest\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\"\xcc\x01\n" +
	"\x14PodmanPlayAssignment\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.kastellan.agent.v1alpha1.ResourceIdentityR\bidentity\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\tR\bmanifest\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\x12'\n" +
	"\x0fupdate_strategy\x18\x04 \x01(\tR\x0eupdateStrategy\"\x9f\x03\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12Z\n" +
	"\x13supported_protocols\x18\x04 \x03(\v2).kastellan.agent.v1alpha1.ProtocolVersionR\x12supportedProtocols\x12F\n" +
	"\aruntime\x18\x05 \x01(\v2,.kastellan.agent.v1alpha1.RuntimeInformationR\aruntime\x12&\n" +
	"\x0flast_session_id\x18\x06 \x01(\tR\rlastSessionId\x124\n" +
	"\x16last_received_revision\x18\a \x01(\x04R\x14lastReceivedRevision\x122\n" +
	"\x15last_applied_revision\x18\b \x01(\x04R\x13lastAppliedRevision\"\xb1\x02\n" +
	"\rOperatorHello\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12V\n" +
	"\x11selected_protocol\x18\x02 \x01(\v2).kastellan.agent.v1alpha1.ProtocolVersionR\x10selectedProtocol\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\rR\x18heartbeatIntervalSeconds\x12A\n" +
	"\x1dstate_report_interval_seconds\x18\x04 \x01(\rR\x1astateReportIntervalSeconds\x12(\n" +
	"\x10server_time_unix\x18\x05 \x01(\x03R\x0eserverTimeUnix\"\x91\x01\n" +
	"\fDesiredState\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12Q\n" +
	"\fpodman_plays\x18\x03 \x03(\v2..kastellan.agent.v1alpha1.PodmanPlayAssignmentR\vpodmanPlays\"\xcf\x01\n" +
	"\x12DesiredStateUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12L\n" +
	"\tadditions\x18\x04 \x03(\v2..kastellan.agent.v1alpha1.PodmanPlayAssignmentR\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x05 \x03(\tR\tdeletions\"\xd2\x01\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12A\n" +
	"\aruntime\x18\x02 \x01(\v2'.kastellan.agent.v1alpha1.RuntimeHealthR\aruntime\x12F\n" +
	"\tworkloads\x18\x03 \x01(\v2(.kastellan.agent.v1alpha1.WorkloadStatusR\tworkloads\x12\x1b\n" +
	"\thost_name\x18\x04 \x01(\tR\bhostName\"\xc8\x01\n" +
	"\rHostInventory\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\x04host\x18\x02 \x01(\v2\".kastellan.agent.v1alpha1.HostInfoR\x04host\x12<\n" +
	"\x06podman\x18\x03 \x01(\v2$.kastellan.agent.v1alpha1.PodmanInfoR\x06podman\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xa8\x01\n" +
	"\x0fReconcileResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12F\n" +
	"\tworkloads\x18\x04 \x03(\v2(.kastellan.agent.v1alpha1.WorkloadResultR\tworkloads\"a\n" +
	"\x10ReconcileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\"\xd5\x01\n" +
	"\x0eWorkloadStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.kastellan.agent.v1alpha1.ResourceIdentityR\bidentity\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12F\n" +
	"\aruntime\x18\x04 \x01(\v2,.kastellan.agent.v1alpha1.RuntimeInformationR\aruntime\"\xc1\x0f\n" +
	"\x0fProtocolMessage\x12G\n" +
	"\vagent_hello\x18\x01 \x01(\v2$.kastellan.agent.v1alpha1.AgentHelloH\x00R\n" +
	"agentHello\x12/\n" +
	"\x12enrollment_request\x18\x02 \x01(\tH\x00R\x11enrollmentRequest\x12C\n" +
	"\theartbeat\x18\x03 \x01(\v2#.kastellan.agent.v1alpha1.HeartbeatH\x00R\theartbeat\x12P\n" +
	"\x0ehost_inventory\x18\x04 \x01(\v2'.kastellan.agent.v1alpha1.HostInventoryH\x00R\rhostInventory\x12V\n" +
	"\x10reconcile_result\x18\x05 \x01(\v2).kastellan.agent.v1alpha1.ReconcileResultH\x00R\x0freconcileResult\x12S\n" +
	"\x0fworkload_status\x18\x06 \x01(\v2(.kastellan.agent.v1alpha1.WorkloadStatusH\x00R\x0eworkloadStatus\x12B\n" +
	"\x1ccertificate_rotation_request\x18\a \x01(\tH\x00R\x1acertificateRotationRequest\x12P\n" +
	"\x0eoperator_hello\x18\b \x01(\v2'.kastellan.agent.v1alpha1.OperatorHelloH\x00R\roperatorHello\x121\n" +
	"\x13enrollment_response\x18\t \x01(\tH\x00R\x12enrollmentResponse\x12M\n" +
	"\rdesired_state\x18\n" +
	" \x01(\v2&.kastellan.agent.v1alpha1.DesiredStateH\x00R\fdesiredState\x12`\n" +
	"\x14desired_state_update\x18\v \x01(\v2,.kastellan.agent.v1alpha1.DesiredStateUpdateH\x00R\x12desiredStateUpdate\x12Y\n" +
	"\x11reconcile_request\x18\f \x01(\v2*.kastellan.agent.v1alpha1.ReconcileRequestH\x00R\x10reconcileRequest\x12D\n" +
	"\x1dcertificate_rotation_response\x18\r \x01(\tH\x00R\x1bcertificateRotationResponse\x12+\n" +
	"\x10connection_close\x18\x0e \x01(\tH\x00R\x0fconnectionClose\x12V\n" +
	"\x10protocol_version\x18\x0f \x01(\v2).kastellan.agent.v1alpha1.ProtocolVersionH\x00R\x0fprotocolVersion\x12Y\n" +
	"\x11resource_identity\x18\x10 \x01(\v2*.kastellan.agent.v1alpha1.ResourceIdentityH\x00R\x10resourceIdentity\x12J\n" +
	"\ferror_detail\x18\x11 \x01(\v2%.kastellan.agent.v1alpha1.ErrorDetailH\x00R\verrorDetail\x12_\n" +
	"\x13runtime_information\x18\x12 \x01(\v2,.kastellan.agent.v1alpha1.RuntimeInformationH\x00R\x12runtimeInformation\x12P\n" +
	"\x0econtainer_info\x18\x13 \x01(\v2'.kastellan.agent.v1alpha1.ContainerInfoH\x00R\rcontainerInfo\x12S\n" +
	"\x0fworkload_result\x18\x14 \x01(\v2(.kastellan.agent.v1alpha1.WorkloadResultH\x00R\x0eworkloadResult\x12P\n" +
	"\x0elocal_workload\x18\x15 \x01(\v2'.kastellan.agent.v1alpha1.LocalWorkloadH\x00R\rlocalWorkload\x12f\n" +
	"\x16podman_play_assignment\x18\x16 \x01(\v2..kastellan.agent.v1alpha1.PodmanPlayAssignmentH\x00R\x14podmanPlayAssignment\x12P\n" +
	"\x0eruntime_health\x18\x17 \x01(\v2'.kastellan.agent.v1alpha1.RuntimeHealthH\x00R\rruntimeHealth\x12A\n" +
	"\thost_info\x18\x18 \x01(\v2\".kastellan.agent.v1alpha1.HostInfoH\x00R\bhostInfo\x12G\n" +
	"\vpodman_info\x18\x19 \x01(\v2$.kastellan.agent.v1alpha1.PodmanInfoH\x00R\n" +
	"podmanInfoB\t\n" +
	"\apayload\"\xa6\x01\n" +
	"\bHostInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\tR\x06memory\x12\x18\n" +
	"\astorage\x18\a \x01(\tR\astorage\"a\n" +
	"\n" +
	"PodmanInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\arootful\x18\x02 \x01(\bR\arootful\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion2t\n" +
	"\rAgentProtocol\x12c\n" +
	"\aConnect\x12).kastellan.agent.v1alpha1.ProtocolMessage\x1a).kastellan.agent.v1alpha1.ProtocolMessage(\x010\x01BQZOgithub.com/useurmind/kastellan/api/proto/kastellan/agent/v1alpha1;agentv1alpha1b\x06proto3"

var (
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescOnce sync.Once
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescData []byte
)

func file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescGZIP() []byte {
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDesc), len(file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDesc)))
	})
	return file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDescData
}

var file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_kastellan_agent_v1alpha1_agent_proto_goTypes = []any{
	(*ProtocolVersion)(nil),      // 0: kastellan.agent.v1alpha1.ProtocolVersion
	(*ResourceIdentity)(nil),     // 1: kastellan.agent.v1alpha1.ResourceIdentity
	(*ErrorDetail)(nil),          // 2: kastellan.agent.v1alpha1.ErrorDetail
	(*RuntimeInformation)(nil),   // 3: kastellan.agent.v1alpha1.RuntimeInformation
	(*RuntimeHealth)(nil),        // 4: kastellan.agent.v1alpha1.RuntimeHealth
	(*ContainerInfo)(nil),        // 5: kastellan.agent.v1alpha1.ContainerInfo
	(*WorkloadResult)(nil),       // 6: kastellan.agent.v1alpha1.WorkloadResult
	(*LocalWorkload)(nil),        // 7: kastellan.agent.v1alpha1.LocalWorkload
	(*PodmanPlayAssignment)(nil), // 8: kastellan.agent.v1alpha1.PodmanPlayAssignment
	(*AgentHello)(nil),           // 9: kastellan.agent.v1alpha1.AgentHello
	(*OperatorHello)(nil),        // 10: kastellan.agent.v1alpha1.OperatorHello
	(*DesiredState)(nil),         // 11: kastellan.agent.v1alpha1.DesiredState
	(*DesiredStateUpdate)(nil),   // 12: kastellan.agent.v1alpha1.DesiredStateUpdate
	(*Heartbeat)(nil),            // 13: kastellan.agent.v1alpha1.Heartbeat
	(*HostInventory)(nil),        // 14: kastellan.agent.v1alpha1.HostInventory
	(*ReconcileResult)(nil),      // 15: kastellan.agent.v1alpha1.ReconcileResult
	(*ReconcileRequest)(nil),     // 16: kastellan.agent.v1alpha1.ReconcileRequest
	(*WorkloadStatus)(nil),       // 17: kastellan.agent.v1alpha1.WorkloadStatus
	(*ProtocolMessage)(nil),      // 18: kastellan.agent.v1alpha1.ProtocolMessage
	(*HostInfo)(nil),             // 19: kastellan.agent.v1alpha1.HostInfo
	(*PodmanInfo)(nil),           // 20: kastellan.agent.v1alpha1.PodmanInfo
}
var file_api_proto_kastellan_agent_v1alpha1_agent_proto_depIdxs = []int32{
	1,  // 0: kastellan.agent.v1alpha1.WorkloadResult.identity:type_name -> kastellan.agent.v1alpha1.ResourceIdentity
	2,  // 1: kastellan.agent.v1alpha1.WorkloadResult.error:type_name -> kastellan.agent.v1alpha1.ErrorDetail
	3,  // 2: kastellan.agent.v1alpha1.WorkloadResult.runtime:type_name -> kastellan.agent.v1alpha1.RuntimeInformation
	5,  // 3: kastellan.agent.v1alpha1.WorkloadResult.containers:type_name -> kastellan.agent.v1alpha1.ContainerInfo
	1,  // 4: kastellan.agent.v1alpha1.LocalWorkload.identity:type_name -> kastellan.agent.v1alpha1.ResourceIdentity
	1,  // 5: kastellan.agent.v1alpha1.PodmanPlayAssignment.identity:type_name -> kastellan.agent.v1alpha1.ResourceIdentity
	0,  // 6: kastellan.agent.v1alpha1.AgentHello.supported_protocols:type_name -> kastellan.agent.v1alpha1.ProtocolVersion
	3,  // 7: kastellan.agent.v1alpha1.AgentHello.runtime:type_name -> kastellan.agent.v1alpha1.RuntimeInformation
	0,  // 8: kastellan.agent.v1alpha1.OperatorHello.selected_protocol:type_name -> kastellan.agent.v1alpha1.ProtocolVersion
	8,  // 9: kastellan.agent.v1alpha1.DesiredState.podman_plays:type_name -> kastellan.agent.v1alpha1.PodmanPlayAssignment
	8,  // 10: kastellan.agent.v1alpha1.DesiredStateUpdate.additions:type_name -> kastellan.agent.v1alpha1.PodmanPlayAssignment
	4,  // 11: kastellan.agent.v1alpha1.Heartbeat.runtime:type_name -> kastellan.agent.v1alpha1.RuntimeHealth
	17, // 12: kastellan.agent.v1alpha1.Heartbeat.workloads:type_name -> kastellan.agent.v1alpha1.WorkloadStatus
	19, // 13: kastellan.agent.v1alpha1.HostInventory.host:type_name -> kastellan.agent.v1alpha1.HostInfo
	20, // 14: kastellan.agent.v1alpha1.HostInventory.podman:type_name -> kastellan.agent.v1alpha1.PodmanInfo
	6,  // 15: kastellan.agent.v1alpha1.ReconcileResult.workloads:type_name -> kastellan.agent.v1alpha1.WorkloadResult
	1,  // 16: kastellan.agent.v1alpha1.WorkloadStatus.identity:type_name -> kastellan.agent.v1alpha1.ResourceIdentity
	3,  // 17: kastellan.agent.v1alpha1.WorkloadStatus.runtime:type_name -> kastellan.agent.v1alpha1.RuntimeInformation
	9,  // 18: kastellan.agent.v1alpha1.ProtocolMessage.agent_hello:type_name -> kastellan.agent.v1alpha1.AgentHello
	13, // 19: kastellan.agent.v1alpha1.ProtocolMessage.heartbeat:type_name -> kastellan.agent.v1alpha1.Heartbeat
	14, // 20: kastellan.agent.v1alpha1.ProtocolMessage.host_inventory:type_name -> kastellan.agent.v1alpha1.HostInventory
	15, // 21: kastellan.agent.v1alpha1.ProtocolMessage.reconcile_result:type_name -> kastellan.agent.v1alpha1.ReconcileResult
	17, // 22: kastellan.agent.v1alpha1.ProtocolMessage.workload_status:type_name -> kastellan.agent.v1alpha1.WorkloadStatus
	10, // 23: kastellan.agent.v1alpha1.ProtocolMessage.operator_hello:type_name -> kastellan.agent.v1alpha1.OperatorHello
	11, // 24: kastellan.agent.v1alpha1.ProtocolMessage.desired_state:type_name -> kastellan.agent.v1alpha1.DesiredState
	12, // 25: kastellan.agent.v1alpha1.ProtocolMessage.desired_state_update:type_name -> kastellan.agent.v1alpha1.DesiredStateUpdate
	16, // 26: kastellan.agent.v1alpha1.ProtocolMessage.reconcile_request:type_name -> kastellan.agent.v1alpha1.ReconcileRequest
	0,  // 27: kastellan.agent.v1alpha1.ProtocolMessage.protocol_version:type_name -> kastellan.agent.v1alpha1.ProtocolVersion
	1,  // 28: kastellan.agent.v1alpha1.ProtocolMessage.resource_identity:type_name -> kastellan.agent.v1alpha1.ResourceIdentity
	2,  // 29: kastellan.agent.v1alpha1.ProtocolMessage.error_detail:type_name -> kastellan.agent.v1alpha1.ErrorDetail
	3,  // 30: kastellan.agent.v1alpha1.ProtocolMessage.runtime_information:type_name -> kastellan.agent.v1alpha1.RuntimeInformation
	5,  // 31: kastellan.agent.v1alpha1.ProtocolMessage.container_info:type_name -> kastellan.agent.v1alpha1.ContainerInfo
	6,  // 32: kastellan.agent.v1alpha1.ProtocolMessage.workload_result:type_name -> kastellan.agent.v1alpha1.WorkloadResult
	7,  // 33: kastellan.agent.v1alpha1.ProtocolMessage.local_workload:type_name -> kastellan.agent.v1alpha1.LocalWorkload
	8,  // 34: kastellan.agent.v1alpha1.ProtocolMessage.podman_play_assignment:type_name -> kastellan.agent.v1alpha1.PodmanPlayAssignment
	4,  // 35: kastellan.agent.v1alpha1.ProtocolMessage.runtime_health:type_name -> kastellan.agent.v1alpha1.RuntimeHealth
	19, // 36: kastellan.agent.v1alpha1.ProtocolMessage.host_info:type_name -> kastellan.agent.v1alpha1.HostInfo
	20, // 37: kastellan.agent.v1alpha1.ProtocolMessage.podman_info:type_name -> kastellan.agent.v1alpha1.PodmanInfo
	18, // 38: kastellan.agent.v1alpha1.AgentProtocol.Connect:input_type -> kastellan.agent.v1alpha1.ProtocolMessage
	18, // 39: kastellan.agent.v1alpha1.AgentProtocol.Connect:output_type -> kastellan.agent.v1alpha1.ProtocolMessage
	39, // [39:40] is the sub-list for method output_type
	38, // [38:39] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_api_proto_kastellan_agent_v1alpha1_agent_proto_init() }
func file_api_proto_kastellan_agent_v1alpha1_agent_proto_init() {
	if File_api_proto_kastellan_agent_v1alpha1_agent_proto != nil {
		return
	}
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes[18].OneofWrappers = []any{
		(*ProtocolMessage_AgentHello)(nil),
		(*ProtocolMessage_EnrollmentRequest)(nil),
		(*ProtocolMessage_Heartbeat)(nil),
		(*ProtocolMessage_HostInventory)(nil),
		(*ProtocolMessage_ReconcileResult)(nil),
		(*ProtocolMessage_WorkloadStatus)(nil),
		(*ProtocolMessage_CertificateRotationRequest)(nil),
		(*ProtocolMessage_OperatorHello)(nil),
		(*ProtocolMessage_EnrollmentResponse)(nil),
		(*ProtocolMessage_DesiredState)(nil),
		(*ProtocolMessage_DesiredStateUpdate)(nil),
		(*ProtocolMessage_ReconcileRequest)(nil),
		(*ProtocolMessage_CertificateRotationResponse)(nil),
		(*ProtocolMessage_ConnectionClose)(nil),
		(*ProtocolMessage_ProtocolVersion)(nil),
		(*ProtocolMessage_ResourceIdentity)(nil),
		(*ProtocolMessage_ErrorDetail)(nil),
		(*ProtocolMessage_RuntimeInformation)(nil),
		(*ProtocolMessage_ContainerInfo)(nil),
		(*ProtocolMessage_WorkloadResult)(nil),
		(*ProtocolMessage_LocalWorkload)(nil),
		(*ProtocolMessage_PodmanPlayAssignment)(nil),
		(*ProtocolMessage_RuntimeHealth)(nil),
		(*ProtocolMessage_HostInfo)(nil),
		(*ProtocolMessage_PodmanInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDesc), len(file_api_proto_kastellan_agent_v1alpha1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kastellan_agent_v1alpha1_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_kastellan_agent_v1alpha1_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_kastellan_agent_v1alpha1_agent_proto_msgTypes,
	}.Build()
	File_api_proto_kastellan_agent_v1alpha1_agent_proto = out.File
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_goTypes = nil
	file_api_proto_kastellan_agent_v1alpha1_agent_proto_depIdxs = nil
}
